{{-- GENERATED BY THE doc:helpers COMMAND; DO NOT EDIT --}}

<li><a href="{{ route('manual.helpers') }}#clamp">clamp</a></li>
<li><a href="{{ route('manual.helpers') }}#cmykColor">cmykColor</a></li>
<li><a href="{{ route('manual.helpers') }}#highByte">highByte</a></li>
<li><a href="{{ route('manual.helpers') }}#isEven">isEven</a></li>
<li><a href="{{ route('manual.helpers') }}#isOdd">isOdd</a></li>
<li><a href="{{ route('manual.helpers') }}#log">log</a></li>
<li><a href="{{ route('manual.helpers') }}#lowByte">lowByte</a></li>
<li><a href="{{ route('manual.helpers') }}#radToDeg">radToDeg</a></li>
<li><a href="{{ route('manual.helpers') }}#randomTrueFalse">randomTrueFalse</a></li>
